/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import AniTest from "./components/views/AniTest"
import LoadingTest from "./components/views/LoadingTest"
import TestEvent1 from "./components/views/TestEvent1"
import TestEvent2 from "./components/views/TestEvent2"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1200;
    static height:number=675;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="LoadingScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("components/views/AniTest.ts",AniTest);
        reg("components/views/LoadingTest.ts",LoadingTest);
        reg("components/views/TestEvent1.ts",TestEvent1);
        reg("components/views/TestEvent2.ts",TestEvent2);
    }
}
GameConfig.init();